services:
  leconfe:
    image: leconfe/leconfe:docker-install
    restart: unless-stopped
    environment:
      PHP_OPCACHE_ENABLE: 1
      PHP_POST_MAX_SIZE: "101M"
      PHP_UPLOAD_MAX_FILE_SIZE: "100M"

      APP_KEY: "base64:yv7ba7W38mH8WC06OAWcokwKhfyaiNR4ranj0gWS7aw="
      APP_INSTALLED: true
      APP_URL: "https://app.leconfe.com"
      APP_FORCE_HTTPS: true

      APP_ADMIN_EMAIL: "admin@leconfe.com"
      APP_ADMIN_PASSWORD: "admin"

      DB_CONNECTION: "mysql"
      DB_HOST: "leconfe-mariadb"
      DB_PORT: "3306"
      DB_DATABASE: "uniska"
      DB_USERNAME: "root"
      DB_PASSWORD: "coklatmanis"

      MAIL_MAILER: "smtp"
      MAIL_HOST: "127.0.0.1"
      MAIL_PORT: "1025"
      # MAIL_USERNAME: null
      # MAIL_PASSWORD: null
      # MAIL_ENCRYPTION: null
      # MAIL_FROM_ADDRESS: "hello@example.com"

      MAX_FILE_UPLOAD_SIZE: 30 # MB
      ACCEPTED_FILE_TYPES: 'pdf,doc,docx,xls,xlsx,odt,txt,xml,jpg,jpeg,csv,png,webp,text/xml,ppt'
    networks:
      - dokploy-network
    volumes:
      - storage-app:/var/www/html/storage/app
      - plugins:/var/www/html/plugins
      - sessions:/var/www/html/storage/framework/sessions
      - logs:/var/www/html/storage/logs
networks:
  dokploy-network:
    external: true
volumes:
  storage-app:
  plugins:
  sessions:
  logs: