name: Docker Publish (Release)
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      docker-tags: "rhmrms/leconfe:${{ github.ref_name }}"
      dockerfile: "./dockerfile"
    secrets: inherit